-- Rollback is intended only before production data is accepted.
DROP TRIGGER IF EXISTS simulation_events_retention ON simulation_events;
DROP TRIGGER IF EXISTS simulations_terminal ON simulations;
DROP TRIGGER IF EXISTS load_mapping_profiles_immutable ON load_mapping_profiles;
DROP TRIGGER IF EXISTS parameter_profiles_immutable ON parameter_profiles;
DROP TRIGGER IF EXISTS worker_jobs_updated_at ON worker_jobs;
DROP TRIGGER IF EXISTS simulations_updated_at ON simulations;
DROP TRIGGER IF EXISTS load_mapping_profiles_updated_at ON load_mapping_profiles;
DROP TRIGGER IF EXISTS parameter_profiles_updated_at ON parameter_profiles;
DROP TRIGGER IF EXISTS datasets_updated_at ON datasets;
DROP FUNCTION IF EXISTS worker_fail_job(TEXT, TEXT, TEXT, JSONB, BOOLEAN);
DROP FUNCTION IF EXISTS worker_commit_simulation(TEXT, TEXT, TEXT, CHAR(64), JSONB, JSONB, JSONB);
DROP FUNCTION IF EXISTS worker_confirm_cancel(TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS worker_complete_preflight(TEXT, TEXT, TEXT, CHAR(64), JSONB, CHAR(64));
DROP FUNCTION IF EXISTS worker_report_stage(TEXT, TEXT, TEXT, TEXT, SMALLINT, JSONB);
DROP FUNCTION IF EXISTS worker_heartbeat(TEXT, TEXT, TEXT, INTEGER);
DROP FUNCTION IF EXISTS worker_claim_next_job(TEXT, TEXT, INTEGER);
DROP FUNCTION IF EXISTS protect_terminal_simulation();
DROP FUNCTION IF EXISTS retain_simulation_events();
DROP FUNCTION IF EXISTS emit_queue_position_events();
DROP FUNCTION IF EXISTS reject_immutable_update();
DROP FUNCTION IF EXISTS set_updated_at();
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS alarm_index;
DROP TABLE IF EXISTS artifacts;
DROP TABLE IF EXISTS simulation_events;
DROP TABLE IF EXISTS worker_jobs;
DROP TABLE IF EXISTS simulation_snapshots;
DROP TABLE IF EXISTS simulations;
DROP TABLE IF EXISTS load_mapping_profiles;
DROP TABLE IF EXISTS parameter_profiles;
DROP TABLE IF EXISTS datasets;
DROP TABLE IF EXISTS scheduler_control;
DROP SEQUENCE IF EXISTS enqueue_sequence;
DROP TABLE IF EXISTS schema_migrations;
