/*
 * Stable display resources. Protocol enums, API fields, CSV fields, hashes,
 * units, artifact names, REFERENCE and CUSTOM remain canonical English.
 */
const additionalEnglishResources = {
  "config.title": "Reference and custom parameter profiles", "config.description": "Reference is immutable. Custom drafts may change only server-declared paths, and saving creates a new version for future tasks.", "config.reference": "Reference profile", "config.custom": "Custom profile", "config.referenceProfileName": "Reference-compatible profile", "profile.referenceCompatible": "Reference-compatible",
  "agent.segment.early": "Early", "agent.segment.middle": "Middle", "agent.segment.late": "Late",
  "param.leaf.nLag": "Lag order", "param.leaf.speedThreshold": "Speed threshold", "param.leaf.currentThreshold": "Current threshold", "param.leaf.medianWindow": "Median window", "param.leaf.madFactor": "MAD factor", "param.leaf.smoothingWindow": "Smoothing window",
  "param.leaf.trainingRatio": "Training ratio", "param.leaf.calibrationRatio": "Calibration ratio", "param.leaf.minimumTraining": "Minimum training samples", "param.leaf.minimumCalibration": "Minimum calibration samples", "param.leaf.minimumTesting": "Minimum testing samples", "param.leaf.agentCount": "Agent count",
  "param.leaf.kNN": "k-nearest neighbors", "param.leaf.adaptiveRatio": "Adaptive ratio", "param.leaf.lengthScale": "Length scale", "param.leaf.signalScale": "Signal scale", "param.leaf.noiseScale": "Noise scale", "param.leaf.minimumRegularization": "Minimum regularization",
  "param.leaf.trendThreshold": "Trend threshold", "param.leaf.maximumMixing": "Maximum mixing", "param.leaf.trendGain": "Trend gain", "param.leaf.maximumStepChange": "Maximum step change",
  "param.leaf.confidence": "Confidence", "param.leaf.calibrationWindow": "Calibration window", "param.leaf.minimumScores": "Minimum scores", "param.leaf.standardDeviationFloor": "Standard-deviation floor", "param.leaf.calibrationScaleMinimum": "Minimum calibration scale", "param.leaf.calibrationScaleMaximum": "Maximum calibration scale", "param.leaf.halfWidthMinimum": "Minimum half width", "param.leaf.halfWidthMaximum": "Maximum half width", "param.leaf.coverageWindow": "Coverage window", "param.leaf.updateMode": "Update mode", "param.leaf.varianceFloor": "Variance floor",
  "param.leaf.baseCenters": "Base centers", "param.leaf.transitionCenters": "Transition centers", "param.leaf.boundaryCenters": "Boundary centers", "param.leaf.transitionQuantile": "Transition quantile", "param.leaf.publicAnchors": "Public anchors", "param.leaf.iterations": "Iterations", "param.leaf.randomSeed": "Random seed",
  "param.leaf.scaleMultiple": "Scale multiple", "param.leaf.minimumWeight": "Minimum weight", "param.leaf.minimumQuerySupport": "Minimum query support", "param.leaf.fullWeightReference": "Full-weight reference", "param.leaf.noiseRatio": "Noise ratio", "param.leaf.choleskyAttempts": "Cholesky attempts", "param.leaf.leaveOneOut": "Leave-one-out",
  "param.leaf.maximumGlobalWeight": "Maximum global weight", "param.leaf.initialImprovement": "Initial improvement", "param.leaf.errorWindow": "Error window", "param.leaf.minimumSamples": "Minimum samples", "param.leaf.winMargin": "Win margin", "param.leaf.varianceWeight": "Variance weight", "param.leaf.winsorQuantile": "Winsor quantile", "param.leaf.globalClearThreshold": "Global clear threshold", "param.leaf.neutralUpperLimit": "Neutral upper limit", "param.leaf.persistence": "Persistence", "param.leaf.riseSmoothing": "Rise smoothing", "param.leaf.fallSmoothing": "Fall smoothing", "param.leaf.disagreementKappa": "Disagreement kappa", "param.leaf.maximumVarianceRatio": "Maximum variance ratio",
  "param.leaf.imbalanceThreshold": "Imbalance threshold", "param.leaf.noticeCount": "Notice count", "param.leaf.warningCount": "Warning count", "param.leaf.alarmCount": "Alarm count", "param.leaf.absoluteCurrentThreshold": "Absolute current threshold", "param.leaf.tensionThreshold": "Tension threshold", "param.leaf.featureDimensionFormula": "Feature dimension formula", "param.leaf.leaveOneOutGlobalModel": "Leave-one-out global model", "param.leaf.predictThenUpdate": "Predict, then update",
  "queue.noWaiting": "No waiting tasks.", "diagnostic.selectedPoint": "Point #{point}", "diagnostic.selectedPointUnavailable": "The selected result point is unavailable for this task.", "aria.chartKeyboard": "Use the left and right arrow keys to select a displayed result point."
};

const additionalChineseResources = {
  "config.title": "参考与自定义参数方案", "config.description": "参考方案不可修改。自定义草稿只能修改服务端已声明路径，保存后创建仅供后续任务使用的新版本。", "config.reference": "参考方案", "config.custom": "自定义方案", "config.referenceProfileName": "参考兼容配置", "profile.referenceCompatible": "参考兼容",
  "agent.segment.early": "早期", "agent.segment.middle": "中期", "agent.segment.late": "后期",
  "param.leaf.nLag": "滞后阶数", "param.leaf.speedThreshold": "速度阈值", "param.leaf.currentThreshold": "电流阈值", "param.leaf.medianWindow": "中位数窗口", "param.leaf.madFactor": "MAD 系数", "param.leaf.smoothingWindow": "平滑窗口",
  "param.leaf.trainingRatio": "训练比例", "param.leaf.calibrationRatio": "校准比例", "param.leaf.minimumTraining": "最少训练样本", "param.leaf.minimumCalibration": "最少校准样本", "param.leaf.minimumTesting": "最少测试样本", "param.leaf.agentCount": "智能体数量",
  "param.leaf.kNN": "近邻数量", "param.leaf.adaptiveRatio": "自适应比例", "param.leaf.lengthScale": "长度尺度", "param.leaf.signalScale": "信号尺度", "param.leaf.noiseScale": "噪声尺度", "param.leaf.minimumRegularization": "最小正则化",
  "param.leaf.trendThreshold": "趋势阈值", "param.leaf.maximumMixing": "最大混合比例", "param.leaf.trendGain": "趋势增益", "param.leaf.maximumStepChange": "最大阶跃变化",
  "param.leaf.confidence": "置信度", "param.leaf.calibrationWindow": "校准窗口", "param.leaf.minimumScores": "最少评分数", "param.leaf.standardDeviationFloor": "标准差下限", "param.leaf.calibrationScaleMinimum": "最小校准尺度", "param.leaf.calibrationScaleMaximum": "最大校准尺度", "param.leaf.halfWidthMinimum": "最小半宽", "param.leaf.halfWidthMaximum": "最大半宽", "param.leaf.coverageWindow": "覆盖率窗口", "param.leaf.updateMode": "更新模式", "param.leaf.varianceFloor": "方差下限",
  "param.leaf.baseCenters": "基础中心", "param.leaf.transitionCenters": "过渡中心", "param.leaf.boundaryCenters": "边界中心", "param.leaf.transitionQuantile": "过渡分位数", "param.leaf.publicAnchors": "公共锚点", "param.leaf.iterations": "迭代次数", "param.leaf.randomSeed": "随机种子",
  "param.leaf.scaleMultiple": "尺度倍数", "param.leaf.minimumWeight": "最小权重", "param.leaf.minimumQuerySupport": "最小查询支持度", "param.leaf.fullWeightReference": "满权重参考", "param.leaf.noiseRatio": "噪声比例", "param.leaf.choleskyAttempts": "Cholesky 尝试次数", "param.leaf.leaveOneOut": "留一法",
  "param.leaf.maximumGlobalWeight": "最大全局权重", "param.leaf.initialImprovement": "初始改进量", "param.leaf.errorWindow": "误差窗口", "param.leaf.minimumSamples": "最少样本", "param.leaf.winMargin": "胜出裕量", "param.leaf.varianceWeight": "方差权重", "param.leaf.winsorQuantile": "Winsor 分位数", "param.leaf.globalClearThreshold": "全局清除阈值", "param.leaf.neutralUpperLimit": "中性上限", "param.leaf.persistence": "持续次数", "param.leaf.riseSmoothing": "上升平滑", "param.leaf.fallSmoothing": "下降平滑", "param.leaf.disagreementKappa": "分歧系数 Kappa", "param.leaf.maximumVarianceRatio": "最大方差比",
  "param.leaf.imbalanceThreshold": "不平衡阈值", "param.leaf.noticeCount": "提示计数", "param.leaf.warningCount": "警告计数", "param.leaf.alarmCount": "告警计数", "param.leaf.absoluteCurrentThreshold": "绝对电流阈值", "param.leaf.tensionThreshold": "张力阈值", "param.leaf.featureDimensionFormula": "特征维度公式", "param.leaf.leaveOneOutGlobalModel": "留一法全局模型", "param.leaf.predictThenUpdate": "先预测，再更新",
  "queue.noWaiting": "暂无等待任务。", "diagnostic.selectedPoint": "点 #{point}", "diagnostic.selectedPointUnavailable": "当前所选结果点在该任务中不可用。", "aria.chartKeyboard": "使用左右方向键选择已显示的结果点。",
  "system.worker": "算法工作器", "workspace.title": "三智能体联邦 GPR 监控", "workspace.description": "智能体 1、智能体 2 和智能体 3 在同一个算法工作器中运行。这不是真实的跨节点联邦。", "workspace.agent": "智能体 {agent}", "workspace.metrics": "当前智能体测试集指标", "workspace.resultTitle": "冻结结果 · 智能体 {agent}", "data.description": "文件仅保留在本地平台。算法工作器预检与仿真使用同一预处理契约。", "data.worker": "算法工作器预检", "data.validating": "算法工作器预检尚未完成。仅在数据集进入 VALID 后展示完整统计。", "data.stats": "算法工作器预检统计", "data.awaiting": "等待算法工作器预检", "data.preflightQueued": "算法工作器预检已排队", "data.preflightRunning": "算法工作器预检正在运行", "data.preflightFinalizing": "算法工作器预检正在完成提交", "data.preflight.queued": "算法工作器预检已排队，尚未开始校验。", "data.preflight.running": "算法工作器预检正在校验。", "data.preflight.validating": "算法工作器预检正在等待当前校验状态。", "data.preflight.finalizing": "算法工作器预检已完成，数据集正在完成提交。", "data.preflight.valid": "算法工作器预检已成功完成。", "data.preflight.invalid": "算法工作器预检未能校验该数据集，无法开始仿真。", "config.agents": "严格为智能体 1 / 2 / 3", "config.noEdits": "当前没有任何共享参数或智能体参数获准编辑。", "config.copy": "创建自定义默认副本", "config.defaultCopyName": "自定义默认副本", "config.saved": "已创建不可变自定义版本 {version}", "state.disabled": "需要有效数据集、已保存参数方案、identity 映射以及严格的智能体 1 / 2 / 3。", "aria.agents": "逻辑智能体", "error.PREFLIGHT_QUEUE_FULL": "算法工作器预检队列已满，请在已有预检完成后重试。", "error.INPUT_INVALID": "算法工作器预检拒绝了数据集输入。", "error.INSUFFICIENT_SAMPLES": "算法工作器预检发现可用样本不足。", "error.NUMERICAL_FAILURE": "算法工作器预检遇到数值计算失败。", "error.RESOURCE_LIMIT": "算法工作器预检达到资源限制。", "error.ARTIFACT_WRITE_FAILED": "算法工作器预检无法写入必需制品。"
};

const additionalCreateEnglishResources = {
  "config.creating": "Creating custom default copy…", "config.created": "Custom default copy {version} created.", "config.createdReadOnly": "Parameter editing remains locked pending allowlist approval."
};

const additionalCreateChineseResources = {
  "config.creating": "正在创建自定义默认副本…", "config.created": "已创建自定义默认副本 {version}。", "config.createdReadOnly": "参数编辑仍需等待白名单批准。"
};

const additionalDraftEnglishResources = {
  "config.title": "Reference and Custom parameter profiles", "config.description": "Reference is immutable. Custom saves a new version for future tasks.", "config.reference": "Reference", "config.custom": "Custom", "config.defaultCopyName": "Custom parameter version", "config.saved": "Saved Custom version {version}.", "config.savedImmutable": "Saved Custom versions are immutable.", "config.savedImmutableHint": "Create an editable draft to save a new version.", "config.referenceLocked": "Reference profile is read-only.", "config.referenceLockedHint": "Reference and fixed S1 constraints cannot be changed.", "config.editable": "Editable draft", "config.editableHint": "Only server-declared parameter paths can be changed. Saving creates a new version for future simulations.", "config.draft": "Draft", "config.customDraft": "Custom draft", "config.editScope": "Edit scope", "config.shared": "Shared", "config.noEditablePaths": "No server-declared editable parameter paths are available.", "config.inherit": "Inherit shared value: {value}", "config.inheritOption": "Inherit shared value", "config.inheritPlaceholder": "Inherit: {value}", "config.saving": "Saving new version…", "config.draftReady": "Draft matches its base version", "config.dirty": "Unsaved changes",
  "config.fixedHint": "S1 hard constraints remain read-only.", "config.s1FixedPath": "S1 hard constraint (read-only)", "config.savedProfiles": "Saved Custom versions", "config.renameLabel": "Display name", "config.aliasLabel": "New Custom alias", "config.aliasHelp": "Required human-readable alias, 1–128 characters. It does not change the version content or hash.", "config.aliasRequired": "Enter a Custom alias before saving.", "config.aliasInvalid": "Use 1–128 characters without control characters.", "config.baseUnavailable": "The reference base for this Custom draft is unavailable.", "config.savedAuthoritative": "Saved alias: {name}", "config.renaming": "Renaming…", "config.renameSaved": "Saved display name: {name}", "action.discard": "Discard draft", "action.resetBase": "Reset to base", "action.restoreDefaults": "Restore defaults", "action.editNew": "Edit as new version", "action.rename": "Rename", "aria.parameterScope": "Parameter edit scope", "error.PARAMETER_OUT_OF_RANGE": "The parameter value is outside its allowed range.", "error.PROFILE_RENAME_UNAVAILABLE": "Renaming is not available from this server yet.", "error.PROFILE_RENAME_INVALID": "Enter a valid display name.",
  "profileSnapshot.title": "Parameter profile", "profileSnapshot.name": "Admission name", "profileSnapshot.version": "Version", "profileSnapshot.hash": "Profile hash", "profileSnapshot.shared": "Shared values", "profileSnapshot.overrides": "Agent overrides", "profileSnapshot.effective": "Effective values", "profileSnapshot.noOverrides": "No Agent-specific overrides", "profileSnapshot.unavailable": "The selected task does not expose the full frozen parameter values.", "profileSnapshot.frozenHint": "This is the immutable parameter snapshot bound to this task. It cannot update a queued, running, or completed task.",
  "queue.title": "Task queue and live status", "queue.description": "The local platform persists one active run and up to ten waiting runs.", "queue.activeSlot": "Active slot", "queue.waiting": "Waiting queue", "queue.capacityHint": "An eleventh waiting request is rejected because the waiting capacity is full.", "queue.activeTask": "Active task", "queue.noActive": "No task is currently active.", "queue.waitingRuns": "Waiting runs", "queue.empty": "No active or waiting tasks. Import a valid dataset and select a saved parameter profile to start a simulation.", "queue.fifo": "FIFO · persisted queue", "queue.position": "Position", "queue.run": "Run ID", "queue.parameters": "Mode / parameters", "queue.dataset": "Dataset", "queue.created": "Created", "queue.status": "Status", "queue.cancel": "Cancel", "queue.cancelActive": "Cancel current task", "queue.agents": "Agent 1 / 2 / 3", "queue.elapsed": "Elapsed", "queue.stage": "Current stage", "queue.events": "Recent events", "queue.eventsEmpty": "No recent event summary is available for this task.", "queue.noStage": "No stage reported", "queue.latestEvent": "Latest event ID: {id}", "queue.cancelled": "Cancellation was requested for {run}.",
  "history.selectRun": "Select a task to inspect its frozen parameter snapshot.", "history.frozenHint": "History details are read-only snapshots.", "history.run": "Task", "history.rerunHint": "A rerun uses this task's original parameter profile by default. Select a new saved version explicitly before creating a new task.", "replay.title": "Frozen replay", "replay.frozenHint": "Replay reads frozen results and the task's immutable parameter snapshot.", "action.openReplay": "Open replay", "action.backHistory": "Back to history",
  "history.eyebrow": "TASK HISTORY", "history.description": "Inspect real terminal tasks, their frozen admission snapshots, and committed local artifacts.", "history.search": "Search", "history.searchPlaceholder": "Run ID or dataset", "history.statusFilter": "Status", "history.modeFilter": "Mode", "history.allStatuses": "All terminal states", "history.allModes": "All modes", "history.count": "{shown} of {total} terminal tasks", "history.loading": "Loading terminal task history…", "history.loadMore": "Load more", "history.empty": "No terminal tasks are available for replay yet. Complete a simulation, then return here.", "history.filterEmpty": "No terminal tasks match the current filters.", "history.finished": "Finished", "history.admission": "Mode / parameter profile", "history.metric": "Fused RMSE", "history.artifacts": "Artifacts", "history.artifactsComplete": "Committed required artifacts", "history.artifactsIncomplete": "Artifacts incomplete", "history.artifactsUnavailable": "Artifacts unavailable", "history.terminalOnly": "Replay is available only for completed tasks.", "history.artifactsRequired": "Replay and downloads require committed required artifacts.", "history.actions": "Actions", "history.inspect": "Inspect", "history.export": "Export", "history.manifest": "Manifest", "history.selected": "Selected frozen task", "history.detailLoading": "Loading the selected frozen task…", "history.artifactName": "Artifact", "history.required": "Required", "history.download": "Download",
  "replay.noSelection": "Select a completed task with committed artifacts from History.", "replay.loading": "Loading frozen replay data…", "replay.unavailable": "Frozen replay data is unavailable for this task.", "replay.diagnostics": "POINT DIAGNOSTICS", "replay.pointDiagnostics": "Current point diagnostics", "replay.noPoint": "Hover over a replay point to inspect its frozen diagnostics.", "replay.point": "Point", "replay.time": "Time", "replay.loadStatus": "Load status", "replay.alarm": "Alarm", "replay.alarms": "ALARMS", "replay.alarmSummary": "Frozen alarm summary", "replay.noAlarms": "No frozen alarm rows are available for this selection.", "replay.points": "{count} frozen replay points", "replay.speed": "Speed", "replay.position": "Position", "replay.positionValue": "Point {current} of {total}", "replay.playing": "Playing", "replay.paused": "Paused", "action.play": "Play", "action.pause": "Pause", "event.received": "State event received", "event.stage": "Stage: {stage}", "event.queuePosition": "Queue position: {position}", "event.waitingCount": "Waiting: {count}",
  "workspace.notConfigured": "No simulation configured", "workspace.onboarding": "Import and validate data, select a saved parameter profile, then start a simulation.", "workspace.goData": "Go to Data", "workspace.goParameters": "Go to Parameters", "workspace.notSelected": "Not selected", "workspace.resultsPending": "Frozen results and diagnostics become available only after this task completes.", "workspace.resultsUnavailable": "Frozen results are not available for this task.", "workspace.liveTask": "Current task", "workspace.noTaskEvents": "No task events are available yet.", "workspace.artifactsIncomplete": "Required result artifacts are incomplete.",
  "connection.connecting": "SSE connecting", "connection.reconnecting": "SSE reconnecting", "connection.offline": "SSE offline",
  "status.invalid": "Invalid", "status.valid": "Valid", "status.validating": "Validating", "status.queued": "Queued", "status.running": "Running", "status.cancelling": "Cancelling", "status.cancelled": "Cancelled", "status.failed": "Failed", "status.failedRecoverable": "Failed (recoverable)", "status.completed": "Completed", "status.ready": "Ready", "status.checking": "Checking", "status.unavailable": "Unavailable", "status.notObserved": "Not observed", "status.warning": "Warning", "status.unknown": "Status unavailable"
};

const additionalDraftChineseResources = {
  "config.title": "参考与自定义参数方案", "config.description": "参考方案不可修改。自定义保存为仅供后续任务使用的新版本。", "config.reference": "参考", "config.custom": "自定义", "config.defaultCopyName": "自定义参数版本", "config.saved": "已保存自定义版本 {version}。", "config.savedImmutable": "已保存的自定义版本不可修改。", "config.savedImmutableHint": "请创建可编辑草稿并另存为新版本。", "config.referenceLocked": "参考方案只读。", "config.referenceLockedHint": "参考方案和固定的 S1 硬约束不可修改。", "config.editable": "可编辑草稿", "config.editableHint": "只能修改服务端已声明的参数路径。保存后会创建仅供新仿真使用的新版本。", "config.draft": "草稿", "config.customDraft": "自定义草稿", "config.editScope": "编辑范围", "config.shared": "共享参数", "config.noEditablePaths": "当前没有服务端声明的可编辑参数路径。", "config.inherit": "继承共享值：{value}", "config.inheritOption": "继承共享值", "config.inheritPlaceholder": "继承：{value}", "config.saving": "正在保存新版本…", "config.draftReady": "草稿与基础版本一致", "config.dirty": "存在未保存修改",
  "config.fixedHint": "固定的 S1 硬约束保持只读。", "config.s1FixedPath": "S1 硬约束（只读）", "config.savedProfiles": "已保存的自定义版本", "config.renameLabel": "显示名称", "config.aliasLabel": "新的自定义别名", "config.aliasHelp": "必填的人类可读别名，长度为 1–128 个字符；不会改变版本内容或哈希。", "config.aliasRequired": "保存前请输入自定义别名。", "config.aliasInvalid": "请输入 1–128 个字符，且不得包含控制字符。", "config.baseUnavailable": "该自定义草稿对应的参考基线不可用。", "config.savedAuthoritative": "已保存别名：{name}", "config.renaming": "正在重命名…", "config.renameSaved": "已保存显示名称：{name}", "action.discard": "放弃草稿", "action.resetBase": "重置为基础版本", "action.restoreDefaults": "恢复默认参数", "action.editNew": "编辑并另存为新版本", "action.rename": "重命名", "aria.parameterScope": "参数编辑范围", "error.PARAMETER_OUT_OF_RANGE": "参数值超出允许范围。", "error.PROFILE_RENAME_UNAVAILABLE": "当前服务端尚不支持重命名。", "error.PROFILE_RENAME_INVALID": "请输入有效的显示名称。",
  "profileSnapshot.title": "参数模板", "profileSnapshot.name": "准入名称", "profileSnapshot.version": "版本", "profileSnapshot.hash": "参数模板哈希", "profileSnapshot.shared": "共享参数值", "profileSnapshot.overrides": "智能体覆盖值", "profileSnapshot.effective": "生效参数值", "profileSnapshot.noOverrides": "没有智能体专属覆盖值", "profileSnapshot.unavailable": "所选任务未提供完整的冻结参数值。", "profileSnapshot.frozenHint": "这是绑定到该任务的不可变参数快照。排队、运行中或已完成任务均不会被热更新。",
  "history.eyebrow": "任务历史", "history.description": "查看真实终态任务、其冻结准入快照和已提交的本地制品。", "history.search": "搜索", "history.searchPlaceholder": "任务 ID 或数据集", "history.statusFilter": "状态", "history.modeFilter": "模式", "history.allStatuses": "全部终态", "history.allModes": "全部模式", "history.count": "共 {total} 个终态任务，显示 {shown} 个", "history.loading": "正在加载终态任务历史…", "history.loadMore": "加载更多", "history.empty": "尚无可回放的终态任务。请先完成一个仿真，再返回此处查看。", "history.filterEmpty": "没有终态任务符合当前筛选条件。", "history.finished": "完成时间", "history.admission": "模式 / 参数模板", "history.metric": "融合 RMSE", "history.artifacts": "制品", "history.artifactsComplete": "必需制品已提交", "history.artifactsIncomplete": "制品不完整", "history.artifactsUnavailable": "制品不可用", "history.terminalOnly": "仅已完成任务可以回放。", "history.artifactsRequired": "回放和下载需要已提交的必需制品。", "history.actions": "操作", "history.inspect": "查看", "history.export": "导出", "history.manifest": "清单", "history.selected": "已选择的冻结任务", "history.detailLoading": "正在加载所选冻结任务…", "history.artifactName": "制品", "history.required": "必需", "history.download": "下载",
  "replay.noSelection": "请在历史记录中选择具有已提交制品的已完成任务。", "replay.loading": "正在加载冻结回放数据…", "replay.unavailable": "该任务没有可用的冻结回放数据。", "replay.diagnostics": "逐点诊断", "replay.pointDiagnostics": "当前点诊断", "replay.noPoint": "悬停在回放曲线上即可查看该点的冻结诊断。", "replay.point": "点", "replay.time": "时间", "replay.loadStatus": "负载状态", "replay.alarm": "告警", "replay.alarms": "告警", "replay.alarmSummary": "冻结告警摘要", "replay.noAlarms": "当前选择没有可用的冻结告警行。", "replay.points": "{count} 个冻结回放点", "replay.speed": "倍速", "replay.position": "位置", "replay.positionValue": "第 {current} / {total} 点", "replay.playing": "正在播放", "replay.paused": "已暂停", "action.play": "播放", "action.pause": "暂停", "event.received": "已收到状态事件", "event.stage": "阶段：{stage}", "event.queuePosition": "队列位置：{position}", "event.waitingCount": "等待数：{count}",
  "workspace.notConfigured": "尚未配置仿真", "workspace.onboarding": "请先导入并校验数据，再选择已保存的参数模板，最后开始仿真。", "workspace.goData": "前往数据导入", "workspace.goParameters": "前往参数配置", "workspace.notSelected": "未选择", "workspace.resultsPending": "该任务完成后才会提供冻结结果和诊断。", "workspace.resultsUnavailable": "该任务没有可用的冻结结果。", "workspace.liveTask": "当前任务", "workspace.noTaskEvents": "尚无可用的任务事件。", "workspace.artifactsIncomplete": "必需的结果制品尚未完整。",
  "connection.connecting": "SSE 正在连接", "connection.reconnecting": "SSE 正在重连", "connection.offline": "SSE 离线",
  "queue.title": "任务队列与实时状态", "queue.description": "本地平台持久化一个运行任务和最多十个等待任务。", "queue.activeSlot": "运行槽位", "queue.waiting": "等待队列", "queue.capacityHint": "第十一个等待请求会因等待容量已满而被拒绝。", "queue.activeTask": "活动任务", "queue.noActive": "当前没有活动任务。", "queue.waitingRuns": "等待任务", "queue.empty": "当前没有运行或等待任务。请导入有效数据集并选择已保存的参数模板后启动仿真。", "queue.fifo": "先进先出 · 已持久化队列", "queue.position": "位置", "queue.run": "任务 ID", "queue.parameters": "模式 / 参数模板", "queue.dataset": "数据集", "queue.created": "创建时间", "queue.status": "状态", "queue.cancel": "取消", "queue.cancelActive": "取消当前任务", "queue.agents": "智能体 1 / 2 / 3", "queue.elapsed": "已用时间", "queue.stage": "当前阶段", "queue.events": "近期事件", "queue.eventsEmpty": "该任务尚无可用的近期事件摘要。", "queue.noStage": "尚未报告阶段", "queue.latestEvent": "最新事件 ID：{id}", "queue.cancelled": "已请求取消任务 {run}。",
  "history.selectRun": "请选择一个任务以查看其冻结参数快照。", "history.frozenHint": "历史详情是只读快照。", "history.run": "任务", "history.rerunHint": "重新运行默认使用该任务的原参数模板。只有明确选择新的已保存版本后，创建的新任务才会使用新版本。", "replay.title": "冻结回放", "replay.frozenHint": "回放读取冻结结果和任务的不可变参数快照。", "action.openReplay": "打开回放", "action.backHistory": "返回历史",
  "status.invalid": "无效", "status.valid": "有效", "status.validating": "校验中", "status.queued": "排队中", "status.running": "运行中", "status.cancelling": "正在取消", "status.cancelled": "已取消", "status.failed": "失败", "status.failedRecoverable": "失败（可恢复）", "status.completed": "已完成", "status.ready": "就绪", "status.checking": "正在检查", "status.unavailable": "不可用", "status.notObserved": "未观测", "status.warning": "警告", "status.unknown": "状态不可用"
};

const resources = {
  en: {
    "nav.workspace": "Workspace", "document.title": "zx/federated-iot-platform:latest · Simulation Console", "nav.data": "Data", "nav.parameters": "Parameters", "nav.queue": "Queue", "nav.history": "History",
    "brand.subtitle": "Federated IoT Simulation · Online Alarm Console", "connection.connected": "SSE connected", "connection.disconnected": "SSE disconnected",
    "action.start": "Start simulation", "action.cancel": "Cancel current", "action.save": "Save as new version", "action.export": "Export JSON", "action.retry": "Retry", "action.reset": "Reset", "action.zoomIn": "Zoom in", "action.zoomOut": "Zoom out", "action.close": "Close",
    "system.web": "Web/API", "system.worker": "Algorithm Worker", "system.database": "Database", "system.ready": "Ready", "system.currentRun": "Current run", "system.stage": "Stage", "system.queue": "Queue", "health.checking": "Checking", "health.ready": "Ready", "health.notObserved": "Not observed", "health.warning": "Warning", "health.unavailable": "Unavailable",
    "workspace.eyebrow": "SIMULATION WORKSPACE", "workspace.title": "Three-Agent Federated GPR Monitoring", "workspace.description": "Agent 1, Agent 2, and Agent 3 run inside one Algorithm Worker. This is not real cross-node federation.",
    "workspace.snapshot": "Simulation configuration snapshot", "workspace.frozen": "Frozen", "workspace.dataset": "Dataset", "workspace.parameterVersion": "Parameter version", "workspace.mapping": "Mapping", "workspace.hash": "Snapshot hash",
    "workspace.metrics": "Current-agent test metrics", "workspace.resultTitle": "Frozen results · Agent {agent}", "workspace.chart": "Predictions, truth, and dynamic intervals", "workspace.interaction": "Wheel to zoom · Drag to pan · Hover for details", "workspace.empty": "No frozen results are selected.",
    "metric.rmse": "Fused RMSE", "metric.mae": "Fused MAE", "metric.r2": "R²", "metric.coverage": "Interval coverage", "metric.bandwidth": "Mean bandwidth", "metric.weight": "Mean global weight", "metric.negative": "Negative transfer rate",
    "legend.truth": "Truth", "legend.local": "Local prediction", "legend.global": "Global prediction", "legend.fused": "Fused prediction", "legend.interval": "Fused interval",
    "data.eyebrow": "LOCAL DATASET", "data.title": "Import and validate a CSV dataset", "data.description": "Files stay on this local platform. Worker preflight uses the same preprocessing contract as a simulation.", "data.choose": "Choose a CSV file", "data.noFileSelected": "No file selected", "data.requirement": "S1 requires exactly: {columns}", "data.limit": "Default upload limit: 500 MB", "data.validating": "Worker preflight is pending. Complete statistics will appear only after it reaches VALID.", "data.valid": "Dataset is VALID", "data.invalid": "Dataset is INVALID", "data.stats": "Worker preflight statistics", "data.awaiting": "Awaiting Worker preflight", "data.preflightNoDataset": "No dataset is available for Worker preflight", "data.preflightQueued": "Worker preflight is queued", "data.preflightRunning": "Worker preflight is running", "data.preflightFinalizing": "Worker preflight is finalizing", "data.noStats": "No complete preprocessing statistics are available yet.", "data.warning": "Warnings", "data.validation": "Validation detail", "data.uploading": "Uploading {name}", "data.bytes": "bytes", "data.preflight.queued": "Worker preflight is queued and has not started validation.", "data.preflight.running": "Worker preflight is running validation.", "data.preflight.validating": "Worker preflight is waiting for its current validation state.", "data.preflight.finalizing": "Worker preflight completed and the dataset is being finalized.", "data.preflight.valid": "Worker preflight completed successfully.", "data.preflight.invalid": "Worker preflight did not validate this dataset. A simulation cannot start.",
    "config.eyebrow": "VERSIONED CONFIGURATION", "config.title": "REFERENCE and CUSTOM parameter profiles", "config.description": "REFERENCE is immutable. CUSTOM can only create a default-value copy while the shared and Agent allowlists are empty.", "config.reference": "REFERENCE", "config.custom": "CUSTOM", "config.readonly": "Read-only", "config.locked": "Default parameters are locked pending human approval of the allowlist.", "config.fixed": "Fixed items", "config.agents": "Exactly Agent 1 / 2 / 3", "config.copy": "Create a CUSTOM default copy", "config.defaultCopyName": "CUSTOM default copy", "config.saved": "Created immutable CUSTOM version {version}", "config.mapping": "Load mapping", "config.noEdits": "No shared or Agent parameter is currently approved for editing.",
    "queue.title": "Task queue", "queue.pending": "Queue status is loading.", "history.title": "History and replay", "history.pending": "History is loading.",
    "state.loading": "Loading", "state.error": "Unable to load this resource", "state.empty": "No data available", "state.cancelRequested": "Cancellation was requested", "state.lastEvent": "Last event ID: {id}", "state.reconnecting": "Reconnecting and correcting state…", "state.disabled": "A valid dataset, saved profile, identity mapping, and exactly Agent 1 / 2 / 3 are required.",
    "error.unknown": "The service returned an unexpected error.", "error.CSV_HEADER_MISMATCH": "The CSV must have the required seven columns in the exact order.", "error.UPLOAD_TOO_LARGE": "The selected file exceeds the configured upload limit.", "error.DATASET_NOT_VALID": "The dataset cannot start a simulation until it is VALID.", "error.PREFLIGHT_QUEUE_FULL": "The Worker preflight queue is full. Try again after a queued preflight finishes.", "error.INPUT_INVALID": "Worker preflight rejected the dataset input.", "error.INSUFFICIENT_SAMPLES": "Worker preflight found too few usable samples.", "error.NUMERICAL_FAILURE": "Worker preflight encountered a numerical failure.", "error.RESOURCE_LIMIT": "Worker preflight reached a resource limit.", "error.ARTIFACT_WRITE_FAILED": "Worker preflight could not write its required artifact.", "error.PARAMETER_NOT_ALLOWED": "This parameter is locked until the approved allowlist is available.", "error.REFERENCE_CONFIG_IMMUTABLE": "REFERENCE cannot be changed.", "error.MAPPING_TYPE_NOT_APPROVED": "Only identity mapping is approved for S1.", "error.QUEUE_FULL": "The waiting queue is full.", "error.RESULT_NOT_READY": "Frozen results are not ready for this task.", "error.RUN_NOT_CANCELLABLE": "This task can no longer be cancelled.",
    "aria.primaryNav": "Primary navigation", "aria.language": "Interface language", "aria.series": "Toggle chart series", "aria.chart": "Interactive prediction and confidence interval chart", "aria.file": "CSV file upload", "aria.parameterGroups": "Parameter groups"
    ,"aria.skip": "Skip to content", "aria.agents": "Logical Agents", "system.preflight": "Preflight", "param.localGpr": "Local GPR", "param.group.featureState": "Feature state", "param.group.cleaning": "Cleaning", "param.group.split": "Split", "param.group.localGp": "Local GP", "param.group.trend": "Trend", "param.group.interval": "Interval", "param.group.anchors": "Anchors", "param.group.support": "Support", "param.group.globalSurrogate": "Global surrogate", "param.group.fusion": "Fusion", "param.group.alarms": "Alarms", "workspace.agent": "Agent {agent}", "diagnostic.eyebrow": "DIAGNOSTICS", "diagnostic.title": "Artifact and preprocessing integrity", "diagnostic.runningRows": "Running rows", "diagnostic.publicAnchors": "Public anchors", "diagnostic.integrity": "Integrity", "event.eyebrow": "SERVER-SENT EVENTS", "event.title": "State synchronization", "event.rest": "Simulation detail is the authoritative state.", "data.hash": "SHA-256", "data.size": "Size", "data.timezone": "Timezone", "data.raw": "Raw", "data.invalidRows": "Invalid", "data.stopped": "Stopped", "data.suspicious": "Suspicious", "data.running": "Running", "data.spikes": "Spike flags", "data.worker": "Worker preflight", "data.status": "Status", "data.contract": "Contract", "data.preprocessing": "Algorithm preprocessing", "config.processing": "Data processing", "config.splits": "Splits & anchors", "config.fusion": "Online fusion", "config.intervals": "Intervals & alarms", "chart.originalPoints": "{count} points", "chart.displayPoints": "{count} display points", "run.defaultDisplayName": "S1 simulation", "tooltip.weightSupport": "Weight / Support", "tooltip.loadAlarm": "Load / Alarm"
  },
  "zh-CN": {
    "nav.workspace": "工作台", "document.title": "zx/federated-iot-platform:latest · 仿真控制台", "nav.data": "数据导入", "nav.parameters": "参数配置", "nav.queue": "任务队列", "nav.history": "历史回放",
    "brand.subtitle": "联邦 IoT 仿真 · 在线告警控制台", "connection.connected": "SSE 已连接", "connection.disconnected": "SSE 已断开",
    "action.start": "开始仿真", "action.cancel": "取消当前任务", "action.save": "保存为新版本", "action.export": "导出 JSON", "action.retry": "重试", "action.reset": "还原", "action.zoomIn": "放大", "action.zoomOut": "缩小", "action.close": "关闭",
    "system.web": "Web/API", "system.worker": "算法 Worker", "system.database": "数据库", "system.ready": "就绪", "system.currentRun": "当前任务", "system.stage": "阶段", "system.queue": "队列", "health.checking": "正在检查", "health.ready": "就绪", "health.notObserved": "未观测", "health.warning": "警告", "health.unavailable": "不可用",
    "workspace.eyebrow": "仿真工作台", "workspace.title": "三 Agent 联邦 GPR 监控", "workspace.description": "Agent 1、Agent 2 和 Agent 3 在一个 Algorithm Worker 中运行。这不是真实的跨节点联邦。",
    "workspace.snapshot": "仿真配置快照", "workspace.frozen": "已冻结", "workspace.dataset": "数据集", "workspace.parameterVersion": "参数版本", "workspace.mapping": "映射", "workspace.hash": "快照哈希",
    "workspace.metrics": "当前 Agent 测试集指标", "workspace.resultTitle": "冻结结果 · Agent {agent}", "workspace.chart": "预测、真值和动态区间", "workspace.interaction": "滚轮缩放 · 拖动平移 · 悬停查看详情", "workspace.empty": "未选择冻结结果。",
    "metric.rmse": "融合 RMSE", "metric.mae": "融合 MAE", "metric.r2": "R²", "metric.coverage": "区间覆盖率", "metric.bandwidth": "平均带宽", "metric.weight": "平均全局权重", "metric.negative": "负迁移率",
    "legend.truth": "真值", "legend.local": "本地预测", "legend.global": "全局预测", "legend.fused": "融合预测", "legend.interval": "融合区间",
    "data.eyebrow": "本地数据集", "data.title": "导入并校验 CSV 数据集", "data.description": "文件仅保留在本地平台。Worker 预检与仿真使用同一预处理契约。", "data.choose": "选择 CSV 文件", "data.noFileSelected": "未选择文件", "data.requirement": "S1 要求严格为：{columns}", "data.limit": "默认上传上限：500 MB", "data.validating": "Worker 预检尚未完成。仅在数据集进入 VALID 后展示完整统计。", "data.valid": "数据集为 VALID", "data.invalid": "数据集为 INVALID", "data.stats": "Worker 预检统计", "data.awaiting": "等待 Worker 预检", "data.preflightNoDataset": "没有可供 Worker 预检的数据集", "data.preflightQueued": "Worker 预检已排队", "data.preflightRunning": "Worker 预检正在运行", "data.preflightFinalizing": "Worker 预检正在完成提交", "data.noStats": "尚无完整预处理统计。", "data.warning": "警告", "data.validation": "校验详情", "data.uploading": "正在上传 {name}", "data.bytes": "字节", "data.preflight.queued": "Worker 预检已排队，尚未开始校验。", "data.preflight.running": "Worker 预检正在校验。", "data.preflight.validating": "Worker 预检正在等待当前校验状态。", "data.preflight.finalizing": "Worker 预检已完成，数据集正在完成提交。", "data.preflight.valid": "Worker 预检已成功完成。", "data.preflight.invalid": "Worker 预检未能校验该数据集，无法开始仿真。",
    "config.eyebrow": "版本化配置", "config.title": "REFERENCE 和 CUSTOM 参数方案", "config.description": "REFERENCE 不可修改。在共享与 Agent 白名单为空时，CUSTOM 只能创建默认参数副本。", "config.reference": "REFERENCE", "config.custom": "CUSTOM", "config.readonly": "只读", "config.locked": "默认参数已锁定，等待人工批准可编辑白名单。", "config.fixed": "固定项", "config.agents": "严格为 Agent 1 / 2 / 3", "config.copy": "创建 CUSTOM 默认副本", "config.defaultCopyName": "CUSTOM 默认副本", "config.saved": "已创建不可变 CUSTOM 版本 {version}", "config.mapping": "负载映射", "config.noEdits": "当前没有任何共享参数或 Agent 参数获准编辑。",
    "queue.title": "任务队列", "queue.pending": "正在加载队列状态。", "history.title": "历史与回放", "history.pending": "正在加载历史记录。",
    "state.loading": "加载中", "state.error": "无法加载此资源", "state.empty": "暂无数据", "state.cancelRequested": "已请求取消", "state.lastEvent": "最新事件 ID：{id}", "state.reconnecting": "正在重连并校正状态…", "state.disabled": "需要有效数据集、已保存参数方案、identity 映射以及严格的 Agent 1 / 2 / 3。",
    "error.unknown": "服务返回了意外错误。", "error.CSV_HEADER_MISMATCH": "CSV 必须按精确顺序包含七个必需列。", "error.UPLOAD_TOO_LARGE": "所选文件超过已配置的上传上限。", "error.DATASET_NOT_VALID": "数据集必须处于 VALID 才能创建仿真。", "error.PREFLIGHT_QUEUE_FULL": "Worker 预检队列已满，请在已有预检完成后重试。", "error.INPUT_INVALID": "Worker 预检拒绝了数据集输入。", "error.INSUFFICIENT_SAMPLES": "Worker 预检发现可用样本不足。", "error.NUMERICAL_FAILURE": "Worker 预检遇到数值计算失败。", "error.RESOURCE_LIMIT": "Worker 预检达到资源限制。", "error.ARTIFACT_WRITE_FAILED": "Worker 预检无法写入必需制品。", "error.PARAMETER_NOT_ALLOWED": "此参数在批准白名单前保持锁定。", "error.REFERENCE_CONFIG_IMMUTABLE": "REFERENCE 不可修改。", "error.MAPPING_TYPE_NOT_APPROVED": "S1 仅批准 identity 映射。", "error.QUEUE_FULL": "等待队列已满。", "error.RESULT_NOT_READY": "此任务的冻结结果尚未就绪。", "error.RUN_NOT_CANCELLABLE": "此任务已不能取消。",
    "aria.primaryNav": "主导航", "aria.language": "界面语言", "aria.series": "切换图表序列", "aria.chart": "交互式预测和置信区间图", "aria.file": "CSV 文件上传", "aria.parameterGroups": "参数分组"
    ,"aria.skip": "跳至内容", "aria.agents": "逻辑 Agent", "system.preflight": "预检", "param.localGpr": "本地 GPR", "param.group.featureState": "特征与状态", "param.group.cleaning": "清洗", "param.group.split": "切分", "param.group.localGp": "本地 GP", "param.group.trend": "趋势", "param.group.interval": "区间", "param.group.anchors": "锚点", "param.group.support": "支持度", "param.group.globalSurrogate": "全局代理", "param.group.fusion": "融合", "param.group.alarms": "告警", "workspace.agent": "Agent {agent}", "diagnostic.eyebrow": "诊断", "diagnostic.title": "制品和预处理完整性", "diagnostic.runningRows": "运行行", "diagnostic.publicAnchors": "公共锚点", "diagnostic.integrity": "完整性", "event.eyebrow": "服务器推送事件", "event.title": "状态同步", "event.rest": "仿真详情是权威状态。", "data.hash": "SHA-256", "data.size": "大小", "data.timezone": "时区", "data.raw": "原始", "data.invalidRows": "无效", "data.stopped": "停机", "data.suspicious": "可疑", "data.running": "运行", "data.spikes": "尖峰标记", "data.worker": "Worker 预检", "data.status": "状态", "data.contract": "契约", "data.preprocessing": "算法预处理", "config.processing": "数据处理", "config.splits": "切分与锚点", "config.fusion": "在线融合", "config.intervals": "区间与告警", "chart.originalPoints": "{count} 个原始点", "chart.displayPoints": "{count} 个显示点", "run.defaultDisplayName": "S1 仿真", "tooltip.weightSupport": "权重 / 支持度", "tooltip.loadAlarm": "负载 / 告警"
  }
};

const productTerminologyEnglishResources = {
  "history.description": "Inspect real terminal tasks, their frozen admission snapshots, and verified local result files.",
  "history.artifacts": "Result files", "history.artifactsComplete": "Required result files verified", "history.artifactsIncomplete": "Result files incomplete", "history.artifactsUnavailable": "Result files unavailable", "history.artifactsRequired": "Replay and downloads require verified required result files.", "history.manifest": "Result file manifest", "history.artifactName": "Result file",
  "replay.noSelection": "Select a completed task with verified result files from History.", "workspace.artifactsIncomplete": "Required result files are incomplete.", "diagnostic.title": "Result files and preprocessing integrity", "error.ARTIFACT_WRITE_FAILED": "Worker preflight could not write its required result file."
};

const productTerminologyChineseResources = {
  "history.description": "查看真实终态任务、其冻结准入快照和已校验的本地结果文件。",
  "history.artifacts": "结果文件", "history.artifactsComplete": "必需结果文件已生成并校验", "history.artifactsIncomplete": "结果文件不完整", "history.artifactsUnavailable": "结果文件不可用", "history.artifactsRequired": "回放和下载需要已生成并校验的必需结果文件。", "history.manifest": "结果文件清单", "history.artifactName": "结果文件",
  "replay.noSelection": "请在历史记录中选择具有已校验结果文件的已完成任务。", "workspace.artifactsIncomplete": "必需结果文件不完整。", "diagnostic.title": "结果文件与预处理完整性", "error.ARTIFACT_WRITE_FAILED": "算法工作器预检无法写入必需结果文件。"
};

/* These overrides keep the current product terminology independent from legacy
   transport identifiers and from the earlier prototype-only labels. */
const currentUiEnglishResources = {
  "config.title": "Reference and Custom parameter profiles", "config.reference": "Reference", "config.custom": "Custom",
  "config.copy": "Create a Custom default copy", "config.defaultCopyName": "Custom default copy", "config.saved": "Created immutable Custom version {version}",
  "workspace.adjustParameters": "Adjust parameters for a new task", "workspace.adjustParametersHint": "The active task is frozen. Saved parameter changes apply only to a new task.",
  "diagnostic.fusionEyebrow": "FUSION DIAGNOSTICS", "diagnostic.fusionTitle": "Fusion weight and global support", "diagnostic.fusionAlpha": "Fusion weight", "diagnostic.globalSupport": "Global support", "diagnostic.recentEyebrow": "RECENT ERROR", "diagnostic.recentTitle": "Recent RMSE and interval half-width",
  "diagnostic.traceEyebrow": "TRACEABILITY", "diagnostic.traceTitle": "Diagnostics and result-file integrity", "diagnostic.noSeries": "No frozen diagnostic series is available for this task.", "diagnostic.latest": "Latest value",
  "event.open": "View server-sent events", "event.close": "Close event panel", "event.drawerTitle": "Server-sent events", "event.drawerDescription": "Run state is corrected from the authoritative simulation detail when the stream reconnects.",
  "event.connection": "Connection", "event.noEvents": "No server-sent events are available for this task.",
  "history.deepLinkInvalid": "The requested task link is invalid.", "history.deepLinkUnavailable": "The requested terminal task is unavailable.", "history.deepLinkLoadFailed": "Unable to load the requested terminal task.",
  "aria.copyHash": "Copy full hash: {value}", "aria.diagnosticSeries": "Diagnostic series legend", "hash.copied": "Hash copied.", "hash.copyFailed": "Unable to copy the hash. Inspect the complete value in this button.",
  "param.leaf.absoluteTensionThreshold": "Absolute tension threshold", "param.leaf.stdFloor": "Standard deviation floor", "param.leaf.agentOverrideWhitelist": "Agent override whitelist",
  "nav.queueWaiting": "Queue ({count} waiting)",
  "workspace.runningLive": "Running live", "workspace.completedRun": "Completed run", "workspace.elapsed": "Elapsed {value}", "workspace.openEvents": "View live events", "workspace.configureNew": "Configure a new run", "workspace.runConfiguration": "RUN CONFIGURATION", "workspace.snapshotTitle": "Simulation configuration snapshot", "workspace.railLocalGpr": "Local GPR", "workspace.railDataProcessing": "Data processing", "workspace.railSplitsAnchors": "Splits and anchors", "workspace.railOnlineFusion": "Online fusion", "workspace.railIntervalsAlarms": "Intervals and alarms",
  "diagnostic.pointSynchronized": "Point-synchronized", "diagnostic.window": "Window {count}", "diagnostic.localRmse": "Local RMSE", "diagnostic.globalRmse": "Global RMSE", "diagnostic.intervalHalfWidth": "Interval half-width", "diagnostic.alarmsEyebrow": "ALARM TIMELINE", "diagnostic.alarmsTitle": "Alarms and load status", "diagnostic.noAlarms": "No frozen alarms are available for this task.", "diagnostic.alarmsUnavailable": "Alarm data is unavailable for this task.", "diagnostic.alarmType": "Type", "diagnostic.pointLocator": "Agent {agent} · Point #{point}", "diagnostic.preprocessing": "Preprocessing", "diagnostic.agentSplit": "Agent {agent} split", "diagnostic.anchors": "Public anchors", "diagnostic.resultFiles": "Result files", "diagnostic.filesUnavailable": "Result-file metadata is unavailable for this task.", "diagnostic.manifest": "Manifest SHA-256", "diagnostic.summaryHash": "Preflight summary SHA-256", "diagnostic.timeRange": "Time range", "diagnostic.sampling": "Sampling",
  "diagnostic.preprocessingSpikes": "Spike flags: {count}", "diagnostic.trainCalibrationTest": "Train / Calibration / Test", "diagnostic.loo": "LOO: {value}", "diagnostic.supportFallbacks": "Support fallbacks: {count}", "diagnostic.alarmDetails": "Alarm details", "diagnostic.alarmTime": "Time", "diagnostic.alarmLevel": "Level", "diagnostic.alarmAgent": "Agent", "diagnostic.originalRunningIndex": "Original running index", "diagnostic.pointLocatorLabel": "Point locator", "diagnostic.alarmReasons": "Reasons", "diagnostic.alarmNoReasons": "No reasons were reported for this alarm.", "alarm.unknownType": "Unspecified alarm type", "alarm.type.loadImbalance": "Load imbalance", "alarm.type.heavyLoad": "Heavy load", "alarm.type.lightLoad": "Light load", "alarm.type.upperBound": "Above fused upper bound", "alarm.type.overall": "Overall alarm",
  "diagnostic.loadDistributionUnavailable": "Load-status distribution is unavailable for this task.", "diagnostic.loadDistributionDisplayed": "Based on {count} displayed points", "diagnostic.loadDistributionAuthoritative": "Run load-status distribution", "diagnostic.alarmsLoaded": "{shown} of {total} loaded", "diagnostic.viewManifest": "View result file manifest and SHA-256", "diagnostic.manifestDialogTitle": "Result file manifest and SHA-256", "diagnostic.manifestDialogDescription": "{count} registered result files · {integrity}", "diagnostic.registeredFiles": "{count} registered result files", "load.normal": "Normal", "load.light": "Light", "load.heavy": "Heavy",
  "alarm.notice": "Notice", "alarm.warning": "Warning", "alarm.alarm": "Alarm", "alarm.none": "None", "alarm.unknown": "Unknown alarm level",
  "data.identity": "Dataset identity", "data.displayName": "Display name", "data.fileName": "File name", "data.timeRange": "Time range", "data.sampling": "Sampling",
  "data.eyebrow": "DATASET INTAKE", "data.title": "Data Import and Strict Validation", "data.description": "The source file is stored read-only with SHA-256. S1 accepts exactly seven columns with no field mapping or silent sorting.",
  "data.offlineScope": "S1 · Offline CSV", "data.dropTitle": "Drop a CSV here or click to browse", "data.dropHint": "Maximum 500 MB · The file never leaves the local system", "data.requiredHeader": "Required header", "data.selectedEyebrow": "SELECTED DATASET", "data.noDatasetSelected": "No dataset selected", "data.validationEyebrow": "VALIDATION REPORT", "data.validationTitle": "Import validation and preprocessing boundary", "data.useDataset": "Use this dataset → Parameters", "data.check": "Check", "data.result": "Result", "data.details": "Details", "data.record": "Record", "data.headerCheck": "Required seven-column header", "data.numericCheck": "Numeric conversion", "data.timeCheck": "Time range", "data.integrityCheck": "Source integrity", "data.preflightCheck": "Worker preflight", "data.verified": "Verified", "data.notReported": "Not reported", "data.sourceRecorded": "Source values preserved", "data.headerDetails": "Names, order, and case from the dataset record", "data.numericDetails": "{count} invalid numeric rows recorded", "data.timeDetails": "Parsed range: {range}", "data.integrityDetails": "Dataset SHA-256 and preprocessing summary hash", "data.preflightDetails": "{contract} · summary hash verified", "data.awaitingDetails": "The dataset record is waiting for authoritative Worker preflight.", "data.failedDetails": "Worker preflight reported a terminal failure.", "data.keep": "Retain", "data.review": "Review", "data.startBlocked": "Start blocked", "data.readyForParameters": "Ready for parameters"
};

const currentUiChineseResources = {
  "config.title": "参考与自定义参数方案", "config.reference": "参考", "config.custom": "自定义",
  "config.copy": "创建自定义默认副本", "config.defaultCopyName": "自定义默认副本", "config.saved": "已创建不可变的自定义版本 {version}",
  "workspace.adjustParameters": "调整新任务参数", "workspace.adjustParametersHint": "当前任务已冻结。保存的参数修改只会应用于新任务。",
  "diagnostic.fusionEyebrow": "融合诊断", "diagnostic.fusionTitle": "融合权重与全局支持度", "diagnostic.fusionAlpha": "融合权重", "diagnostic.globalSupport": "全局支持度", "diagnostic.recentEyebrow": "近期误差", "diagnostic.recentTitle": "近期 RMSE 与区间半宽", 
  "diagnostic.traceEyebrow": "可追溯性", "diagnostic.traceTitle": "诊断与结果文件完整性", "diagnostic.noSeries": "该任务没有可用的冻结诊断序列。", "diagnostic.latest": "最新值",
  "event.open": "查看服务器推送事件", "event.close": "关闭事件面板", "event.drawerTitle": "服务器推送事件", "event.drawerDescription": "重连后会依据权威仿真详情校正任务状态。",
  "event.connection": "连接", "event.noEvents": "该任务没有可用的服务器推送事件。",
  "history.deepLinkInvalid": "请求的任务链接无效。", "history.deepLinkUnavailable": "请求的终态任务不可用。", "history.deepLinkLoadFailed": "无法加载请求的终态任务。",
  "aria.copyHash": "复制完整哈希：{value}", "aria.diagnosticSeries": "诊断序列图例", "hash.copied": "哈希已复制。", "hash.copyFailed": "无法复制哈希，请在此按钮中查看完整值。",
  "param.leaf.absoluteTensionThreshold": "绝对张力阈值", "param.leaf.stdFloor": "标准差下限", "param.leaf.agentOverrideWhitelist": "智能体覆盖白名单",
  "nav.queueWaiting": "队列（{count} 个等待）",
  "workspace.runningLive": "实时运行中", "workspace.completedRun": "已完成任务", "workspace.elapsed": "已用 {value}", "workspace.openEvents": "查看实时事件", "workspace.configureNew": "配置新任务", "workspace.runConfiguration": "任务配置", "workspace.snapshotTitle": "仿真配置快照", "workspace.railLocalGpr": "本地 GPR", "workspace.railDataProcessing": "数据处理", "workspace.railSplitsAnchors": "切分与锚点", "workspace.railOnlineFusion": "在线融合", "workspace.railIntervalsAlarms": "区间与告警",
  "diagnostic.pointSynchronized": "按点同步", "diagnostic.window": "窗口 {count}", "diagnostic.localRmse": "本地 RMSE", "diagnostic.globalRmse": "全局 RMSE", "diagnostic.intervalHalfWidth": "区间半宽", "diagnostic.alarmsEyebrow": "告警时间线", "diagnostic.alarmsTitle": "告警与负载状态", "diagnostic.noAlarms": "该任务没有可用的冻结告警。", "diagnostic.alarmsUnavailable": "该任务的告警数据不可用。", "diagnostic.alarmType": "类型", "diagnostic.pointLocator": "智能体 {agent} · 点 #{point}", "diagnostic.preprocessing": "预处理", "diagnostic.agentSplit": "智能体 {agent} 切分", "diagnostic.anchors": "公共锚点", "diagnostic.resultFiles": "结果文件", "diagnostic.filesUnavailable": "该任务的结果文件元数据不可用。", "diagnostic.manifest": "清单 SHA-256", "diagnostic.summaryHash": "预检摘要 SHA-256", "diagnostic.timeRange": "时间范围", "diagnostic.sampling": "采样", 
  "diagnostic.preprocessingSpikes": "尖峰标记：{count}", "diagnostic.trainCalibrationTest": "训练 / 校准 / 测试", "diagnostic.loo": "留一法：{value}", "diagnostic.supportFallbacks": "支持度回退：{count}", "diagnostic.alarmDetails": "告警详情", "diagnostic.alarmTime": "时间", "diagnostic.alarmLevel": "级别", "diagnostic.alarmAgent": "智能体", "diagnostic.originalRunningIndex": "原始运行索引", "diagnostic.pointLocatorLabel": "点定位", "diagnostic.alarmReasons": "原因", "diagnostic.alarmNoReasons": "该告警没有已报告原因。", "alarm.unknownType": "未指定告警类型", "alarm.type.loadImbalance": "负载不平衡", "alarm.type.heavyLoad": "重负载", "alarm.type.lightLoad": "轻负载", "alarm.type.upperBound": "超过融合上界", "alarm.type.overall": "整体告警",
  "diagnostic.loadDistributionUnavailable": "该任务没有可用的负载状态分布。", "diagnostic.loadDistributionDisplayed": "基于 {count} 个已显示点", "diagnostic.loadDistributionAuthoritative": "任务负载状态分布", "diagnostic.alarmsLoaded": "已加载 {shown} / {total}", "diagnostic.viewManifest": "查看结果文件清单与 SHA-256", "diagnostic.manifestDialogTitle": "结果文件清单与 SHA-256", "diagnostic.manifestDialogDescription": "已登记 {count} 个结果文件 · {integrity}", "diagnostic.registeredFiles": "已登记 {count} 个结果文件", "load.normal": "正常", "load.light": "轻负载", "load.heavy": "重负载",
  "alarm.notice": "提示", "alarm.warning": "警告", "alarm.alarm": "告警", "alarm.none": "无", "alarm.unknown": "未知告警级别",
  "data.identity": "数据集标识", "data.displayName": "显示名称", "data.fileName": "文件名", "data.timeRange": "时间范围", "data.sampling": "采样",
  "data.eyebrow": "数据集导入", "data.title": "数据导入与严格校验",
  "data.offlineScope": "S1 · 离线 CSV", "data.dropTitle": "拖放 CSV 文件到此处，或点击浏览", "data.dropHint": "最大 500 MB · 文件不会离开本地系统", "data.requiredHeader": "必需表头", "data.selectedEyebrow": "已选数据集", "data.noDatasetSelected": "尚未选择数据集", "data.validationEyebrow": "校验报告", "data.validationTitle": "导入校验与预处理边界", "data.useDataset": "使用此数据集 → 参数配置", "data.check": "检查项", "data.result": "结果", "data.details": "详情", "data.record": "记录", "data.headerCheck": "必需七列表头", "data.numericCheck": "数值转换", "data.timeCheck": "时间范围", "data.integrityCheck": "源文件完整性", "data.preflightCheck": "算法工作器预检", "data.verified": "已校验", "data.notReported": "未报告", "data.sourceRecorded": "源值已保留", "data.headerDetails": "来自数据集记录的名称、顺序和大小写", "data.numericDetails": "已记录 {count} 条无效数值行", "data.timeDetails": "解析范围：{range}", "data.integrityDetails": "数据集 SHA-256 与预处理摘要哈希", "data.preflightDetails": "{contract} · 摘要哈希已校验", "data.awaitingDetails": "数据集记录正在等待权威算法工作器预检。", "data.failedDetails": "算法工作器预检报告了终态失败。", "data.keep": "保留", "data.review": "检查", "data.startBlocked": "禁止启动", "data.readyForParameters": "可配置参数"
};

const currentUiChineseDataPreflightResources = {
  "data.description": "源文件按 SHA-256 只读保存；S1 严格接受七列，不进行字段映射或静默排序。",
  "data.validating": "算法工作器预检尚未完成。数据集校验通过后才显示完整统计。",
  "data.valid": "数据集校验通过",
  "data.invalid": "数据集校验未通过",
  "data.stats": "算法工作器预检统计",
  "data.awaiting": "等待算法工作器预检",
  "data.preflightNoDataset": "尚无数据集可进行算法工作器预检。",
  "data.preflightQueued": "算法工作器预检已排队",
  "data.preflightRunning": "算法工作器预检正在运行",
  "data.preflightFinalizing": "算法工作器预检已完成，正在提交数据集记录",
  "data.preflight.queued": "算法工作器预检已排队，尚未开始校验。",
  "data.preflight.running": "算法工作器预检正在校验。",
  "data.preflight.validating": "算法工作器预检正在等待当前校验状态。",
  "data.preflight.finalizing": "算法工作器预检已完成，正在提交数据集记录。",
  "data.preflight.valid": "算法工作器预检已完成，数据集校验通过。",
  "data.preflight.invalid": "算法工作器预检未通过，数据集校验失败，无法开始仿真。"
};

const currentUiEnglishDataContractResources = {
  "data.fileName": "Original filename",
  "data.preflightJob": "Preflight job",
  "data.preflightStatus": "Preflight status",
  "data.preflightQueuePosition": "Queue position",
  "data.preflightStage": "Worker stage",
  "data.preflightAttempt": "Attempt ID",
  "data.preflightLease": "Lease state",
  "data.preflightEvent": "Latest event ID",
  "data.validationStarted": "Validation started",
  "data.validationFinished": "Validation finished",
  "data.diagnosticId": "Diagnostic ID",
  "data.errorStage": "Failure stage",
  "data.preprocessingContract": "Preprocessing contract",
  "data.preprocessingSchema": "Schema version",
  "data.filterPath": "Filter path",
  "data.preprocessingParameters": "Preprocessing parameters",
  "data.inputHash": "Input SHA-256"
};

const currentUiChineseDataContractResources = {
  "data.fileName": "原始文件名",
  "data.preflightJob": "预检作业",
  "data.preflightStatus": "预检状态",
  "data.preflightQueuePosition": "队列位置",
  "data.preflightStage": "算法工作器阶段",
  "data.preflightAttempt": "尝试 ID",
  "data.preflightLease": "租约状态",
  "data.preflightEvent": "最新事件 ID",
  "data.validationStarted": "校验开始时间",
  "data.validationFinished": "校验完成时间",
  "data.diagnosticId": "诊断 ID",
  "data.errorStage": "失败阶段",
  "data.preprocessingContract": "预处理契约",
  "data.preprocessingSchema": "结构版本",
  "data.filterPath": "过滤路径",
  "data.preprocessingParameters": "预处理参数",
  "data.inputHash": "输入 SHA-256"
};

Object.assign(resources.en, additionalEnglishResources, additionalCreateEnglishResources, additionalDraftEnglishResources);
Object.assign(resources["zh-CN"], additionalChineseResources, additionalCreateChineseResources, additionalDraftChineseResources);
Object.assign(resources.en, productTerminologyEnglishResources);
Object.assign(resources["zh-CN"], productTerminologyChineseResources);
Object.assign(resources.en, currentUiEnglishResources);
Object.assign(resources["zh-CN"], currentUiChineseResources);
Object.assign(resources["zh-CN"], currentUiChineseDataPreflightResources);
Object.assign(resources.en, currentUiEnglishDataContractResources);
Object.assign(resources["zh-CN"], currentUiChineseDataContractResources);

export const languages = ["en", "zh-CN"];
// Language is presentation-only; application startup supplies English for every fresh page load.
export function createI18n(initialLanguage = "en") {
  let language = initialLanguage === "zh-CN" ? "zh-CN" : "en";
  return {
    get language() { return language; },
    setLanguage(nextLanguage) { language = nextLanguage === "zh-CN" ? "zh-CN" : "en"; },
    t(key, variables = {}) {
      const template = resources[language][key] ?? resources.en[key] ?? key;
      return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, name) => String(variables[name] ?? `{${name}}`));
    }
  };
}
